services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=vZhDmz2B9rsUtuPkDBmLkb7sXsb3DF4
      - POSTGRES_DB=DapperDB
    volumes:
      - ./Temp/postgres/data:/var/lib/postgresql
    command: 
      - "postgres"
      - "-c"
      - "wal_level=logical"

  zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    platform: linux/x86_64
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - ./Temp/zookeeper_data:/zookeeper_data

  kafka:
    image: debezium/kafka:2.7.3.Final
    platform: linux/x86_64
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./Temp/kafka_data:/kafka/data
      - ./Temp/kafka_logs:/kafka/logs
      - ./Temp/kafka_config:/kafka/config

  connect:
    image: debezium/connect:2.7.3.Final
    platform: linux/x86_64
    container_name: connect
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - zookeeper
      - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8090"
    restart: always
    environment:
      - SERVER_PORT=8090
      - KAFKA_CLUSTERS_0_NAME=localhost
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092

  debezium-ui:
    image: debezium/debezium-ui:latest
    platform: linux/x86_64
    container_name: debezium-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eD7AtQToy8fzxdxfofcH3nkez3qkfWpV
      MONGO_INITDB_DATABASE: ForexData
    volumes:
      - ./Temp/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 2MYR3uiphKnrF3ZWMMAVU8PpENyFDbBR
      ME_CONFIG_BASICAUTH_USERNAME: 'root'
      ME_CONFIG_BASICAUTH_PASSWORD: 'eD7AtQToy8fzxdxfofcH3nkez3qkfWpV'
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_URL: mongodb://root:eD7AtQToy8fzxdxfofcH3nkez3qkfWpV@mongo:27017/

  gatewap.api:
    container_name: tcmb-forex-gateway-api
    restart: always
    build: 
      context: .
      dockerfile: src/TcmbForexApi.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5277:80"

  write.api:
    container_name: tcmb-forex-write-api
    restart: always
    build: 
      context: .
      dockerfile: src/TcmbForexApi.WriteAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5067:80"
    depends_on:
      - postgres

  read.api:
    container_name: tcmb-forex-read-api
    restart: always
    build: 
      context: .
      dockerfile: src/TcmbForexApi.ReadAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5228:80"

  consumer.forex.rate:
    container_name: tcmb-forex-consumer-forex-rate
    restart: always
    build: 
      context: .
      dockerfile: src/TcmbForexApi.Consumers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - kafka

  